default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  # host: postgres => dava falha: Could not translate host name "postgres" to address: 
  user: postgres
  POSTGRES_USER: 'postgres'
  POSTGRES_HOST_AUTH_METHOD: trust

development:
  <<: *default
  database: petadmin_development

test:
  <<: *default
  database: petadmin_exchance_test

production:
  <<: *default
  database: petadmin_exchance_production